In [14]:
import numpy as np
#Create a 1D NumPy array with integers from 1 to 10.

arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [18]:
#Create a 2D array of shape (3, 3) with numbers from 1 to 9.
arr2 = np.arange(1,10).reshape(3,3)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
#Create a NumPy array of 5 zeros and another of 5 ones.
five = np.ones([5,5])
print(five)

zero = np.zeros([5,5])
print(zero)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
#Find the shape, size, and datatype of a NumPy array.
print(arr.shape)
print(arr.size)
print(arr.dtype)

(10,)
10
int64


In [27]:
#Add 5 to every element in a NumPy array.
print(arr+5)
print(arr2+5)

[ 6  7  8  9 10 11 12 13 14 15]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [33]:
#Compute the sum, mean, and standard deviation of a NumPy array.
print(arr.sum())
print(arr2.sum())

print(arr.mean())
print(arr2.mean())

print(arr.std())
print(arr2.std())

55
45
5.5
5.0
2.8722813232690143


In [35]:
#Extract the 2nd and 4th elements from a 1D array.
print(arr[[1,3]])

[2 4]


In [36]:
#Extract the first two rows and last two columns from a 2D array.

In [38]:
arr2[:2,-2:]

array([[2, 3],
       [5, 6]])

In [41]:
#Reshape a 1D array of size 9 into a 3x3 matrix.
print(arr[:9].reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
#My Random Array
dummy = np.array([1,2,3,4,5,6,7,8,9])
dummy
re_dummy = dummy.reshape(3,3)
re_dummy[2:,:2]

array([[7, 8]])

In [58]:
#Create a 5x5 matrix with random values and replace all values greater than 0.5 with 1.
f = np.random.randint(1,11,(5,5))
f[f> 0.5] = 1
f

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])