In [1]:
#linear Algebra
import numpy as np

a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [4]:
a*b
#when you multiply directly following erro will be shown => ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [6]:
#for multiplying different matrix use following function
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [8]:
#Find the determinant
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [10]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#