In [3]:
import numpy as np

a = np.array([1,2,3,4,5])
b = a.copy()
b[0]=10
print(b)
print(a)

[10  2  3  4  5]
[1 2 3 4 5]


In [7]:
#array mathematical operation
a =np.array([1,2,3,4,5])
print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a**2)


[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]


In [8]:
b = np.array([1,2,3,4,5])
c = np.array([6,7,8,9,10])
print(b+c)

[ 7  9 11 13 15]
