In [8]:
import numpy as np
a = np.ones((5,5))
print(a)

z = np.zeros((3,3))
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [11]:
a[1:-1,1:-1]=z
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
arr1 = np.ones((4,4))
print(arr1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
arr2 = np.zeros((2,2))
print(arr2)

[[0. 0.]
 [0. 0.]]


In [34]:
arr1[1:3,1:3] = arr2
print(arr1)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [ ]:
arr3 = np.zeros((4,4))
print(arr3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [35]:
arr4 = np.ones((2,2))
print(arr4)

[[1. 1.]
 [1. 1.]]


In [36]:
arr3[1:3,1:3] = arr4
print(arr3)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [ ]:
arr5 = np.ones((4,4))
print(arr5)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
arr6 = np.zeros((4,4))
arr6[:,0 ]= 1
arr6[:,3 ]= 1
arr6[2:,: ]= 1
print(arr6)


[[1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
arr7=np.zeros((4,4))
arr7[:,0] = 1
arr7[:,3] = 1
arr7[2,:] = 1
arr7[3,:] = 1
#arr7[2:,:] = 0
print(arr7)
#desured matrix got you made it champ!!!!

[[1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [68]:
#desired matrix
arr8 = np.zeros((4,4))
arr8[:,0]=1
arr8[:,1]=1
arr8[0,:]=1
arr8[1,:]=1
print(arr8)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]


In [ ]:
a = np.array([1,2,3,4,5])
b = a
b[0] = 100
print(b)
print(a)
#through this method a is didturbed when a particular value of b is changed


[100   2   3   4   5]
[100   2   3   4   5]
