In [3]:
import numpy as np

a = np.array([1,2,3,4,5])
a


array([1, 2, 3, 4, 5])

In [5]:
b = np.array([[1.2,2.4,3.6],[1.8,3.6,4.5]])
b

array([[1.2, 2.4, 3.6],
       [1.8, 3.6, 4.5]])

In [6]:
c = np.array([[45,78,9,6],[ 78,41,2,5]])
c

array([[45, 78,  9,  6],
       [78, 41,  2,  5]])

In [23]:
c.ndim

2

In [8]:
b.ndim

2

In [ ]:
c = np.array([[45,78,9,6],[ 78,41,2,5],[7,5,6,9]])


2

In [22]:
# .ndim is used to get no of dimensions
c.ndim


2

In [13]:
#Get Shape
a.shape

(5,)

In [19]:
c.dtype


dtype('int64')

In [18]:
b.dtype

dtype('float64')

In [21]:
#Get Size
b.itemsize

8