In [3]:
import numpy as np

a = np.array([1,2,3,4,5])
a


array([1, 2, 3, 4, 5])

In [5]:
b = np.array([[1.2,2.4,3.6],[1.8,3.6,4.5]])
b

array([[1.2, 2.4, 3.6],
       [1.8, 3.6, 4.5]])

In [6]:
c = np.array([[45,78,9,6],[ 78,41,2,5]])
c

array([[45, 78,  9,  6],
       [78, 41,  2,  5]])