In [11]:
import numpy as np

a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [33]:
#Getting a specific row
a[1, :]

array([ 6,  7,  8,  9, 10])

In [14]:
#GEtting a specific column
a[:,2]

array([ 3,  8, 13])

In [34]:
a.ndim

2

In [ ]:
#Printing element from specific range within particular column
a[0:3,1]

array([ 2,  7, 12])

In [21]:
#Printing element from specific range within particular row
a[0,0:3]

array([1, 2, 3])

In [24]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [47]:
b[0,2] = 20
b.ndim

2

In [3]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]]) #np.array should be palced infront of square brackets
d.ndim
d.itemsize

NameError: name 'np' is not defined