In [13]:
#Create a 3x3 NumPy array with random integers between 1 and 100. 
# Replace all even numbers in the array with -1.

import numpy as np

a = np.random.randint(1,101,(3,3))
a[a%2 ==0] = -1
a

array([[-1, 75, -1],
       [-1, 67, -1],
       [-1, 17, -1]])

In [9]:
#Write a function to calculate the row-wise sum and column-wise sum of a given 4x4 NumPy array.

b = np.random.randint(1,11,(4,4))
b

row_sum = b.sum(axis=0)
col_sum = b.sum(axis=1)
print("sum of row = ",row_sum)
print("sum of col = ",col_sum)

sum of row =  [17 17 25 25]
sum of col =  [21 15 32 16]


In [15]:
#Create a 1D NumPy array with 20 equally spaced values between 0 and 1. Then, reshape it into a 4x5 2D array.

c = np.linspace(0,1,20)
c
c_reshape = c.reshape(4,5)
c_reshape

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632],
       [0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421],
       [0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211],
       [0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])

In [21]:
#Given two NumPy arrays, A and B, perform the following operations:

    #Element-wise addition
    #Element-wise multiplication
    #Matrix multiplication

a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))

    #Element-wise addition
a+b
    #Element-wise multiplication
a*b
    #Matrix multiplication
matmul = np.matmul(a,b)
matmul


array([[ 74,  53,  53],
       [160, 128,  80],
       [ 54,  43,  27]])

In [24]:
#Write a NumPy program to extract all the unique elements from a given array and sort them in ascending order.
f = np.array([45,78,96,52,14,45,85,78,10,12,10])
sort = np.unique(f)
sort

array([10, 12, 14, 45, 52, 78, 85, 96])

In [24]:
#Create a 1D NumPy array with values ranging from 1 to 100. Then filter and return all the prime numbers from the array.
one_d = np.arange(1,101)

#Function to find prime number
def prime(x):
    count = 0    
    for i in range(1,x+1):
        if x % i == 0:
            count += 1
    if count ==2:
        print(x)
    # else:
    #     print("not prime")

prime_list = []

for num in one_d:
    if prime(num):
        prime_list.append(num)

primes_array = np.array(prime_list)
primes_array

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


array([], dtype=float64)

In [27]:
#Write a NumPy program to find the maximum element along each row and each column of a given 3x4 array.

num_array = np.random.randint(1,10,(3,4))
num_array

row_max = num_array.max(axis=0)
row_min = num_array.min(axis=0)
col_max = num_array.max(axis=1)
col_min = num_array.min(axis=1)

print(row_max)
print(row_min)
print(col_max)
print(col_min)

[4 8 9 9]
[2 5 6 3]
[8 9 9]
[2 4 2]


In [32]:
#Create a 6x6 identity matrix, and then replace all the diagonal elements with the number 7.
arr1 = np.ones((6,6))
np.fill_diagonal(arr1,7)
arr1

array([[7., 1., 1., 1., 1., 1.],
       [1., 7., 1., 1., 1., 1.],
       [1., 1., 7., 1., 1., 1.],
       [1., 1., 1., 7., 1., 1.],
       [1., 1., 1., 1., 7., 1.],
       [1., 1., 1., 1., 1., 7.]])

In [34]:
#Write a function that takes a 2D NumPy array and returns the indices of all elements greater than a given threshold.

gut = np.random.randint(1,101,(4,5))
gut

threshold = 50

indices = np.argwhere(gut>threshold)
print(f"Indices of Elements Greater Than {threshold}:\n", indices)

Indices of Elements Greater Than 50:
 [[0 2]
 [1 2]
 [1 4]
 [2 0]
 [2 1]
 [2 4]
 [3 2]
 [3 3]
 [3 4]]


In [ ]:
#Generate a 5x5 NumPy array with random values and normalize the array (i.e., scale all values to be between 0 and 1).