In [7]:
#Create a 3x3 NumPy array with random integers between 1 and 100. 
# Replace all even numbers in the array with -1.

import numpy as np

a = np.random.randint(1,101,(3,3))
a[a%2 ==0] = -1
a

array([[ 7, -1, -1],
       [89, 21, 71],
       [53, -1, -1]])

In [9]:
#Write a function to calculate the row-wise sum and column-wise sum of a given 4x4 NumPy array.

b = np.random.randint(1,11,(4,4))
b

row_sum = b.sum(axis=0)
col_sum = b.sum(axis=1)
print("sum of row = ",row_sum)
print("sum of col = ",col_sum)

sum of row =  [17 17 25 25]
sum of col =  [21 15 32 16]


In [15]:
#Create a 1D NumPy array with 20 equally spaced values between 0 and 1. Then, reshape it into a 4x5 2D array.

c = np.linspace(0,1,20)
c
c_reshape = c.reshape(4,5)
c_reshape

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632],
       [0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421],
       [0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211],
       [0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])

In [21]:
#Given two NumPy arrays, A and B, perform the following operations:

    #Element-wise addition
    #Element-wise multiplication
    #Matrix multiplication

a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))

    #Element-wise addition
a+b
    #Element-wise multiplication
a*b
    #Matrix multiplication
matmul = np.matmul(a,b)
matmul


array([[ 74,  53,  53],
       [160, 128,  80],
       [ 54,  43,  27]])

In [24]:
#Write a NumPy program to extract all the unique elements from a given array and sort them in ascending order.
f = np.array([45,78,96,52,14,45,85,78,10,12,10])
sort = np.unique(f)
sort

array([10, 12, 14, 45, 52, 78, 85, 96])

In [26]:
#Create a 1D NumPy array with values ranging from 1 to 100. Then filter and return all the prime numbers from the array.
prime = np.linspace(1,101,)
prime

#prime number function

def prime(n):
    

array([  1.        ,   3.04081633,   5.08163265,   7.12244898,
         9.16326531,  11.20408163,  13.24489796,  15.28571429,
        17.32653061,  19.36734694,  21.40816327,  23.44897959,
        25.48979592,  27.53061224,  29.57142857,  31.6122449 ,
        33.65306122,  35.69387755,  37.73469388,  39.7755102 ,
        41.81632653,  43.85714286,  45.89795918,  47.93877551,
        49.97959184,  52.02040816,  54.06122449,  56.10204082,
        58.14285714,  60.18367347,  62.2244898 ,  64.26530612,
        66.30612245,  68.34693878,  70.3877551 ,  72.42857143,
        74.46938776,  76.51020408,  78.55102041,  80.59183673,
        82.63265306,  84.67346939,  86.71428571,  88.75510204,
        90.79591837,  92.83673469,  94.87755102,  96.91836735,
        98.95918367, 101.        ])

In [32]:
def repeat(x):
    count = 0    
    for i in range(1,x+1):
        if x % i ==2:
            count += 1
    if count ==2:
        print("prime")
    else:
        print("not prime")
repeat(5)

not prime
