In [7]:
#Create a 3x3 NumPy array with random integers between 1 and 100. 
# Replace all even numbers in the array with -1.

import numpy as np

a = np.random.randint(1,101,(3,3))
a[a%2 ==0] = -1
a

array([[ 7, -1, -1],
       [89, 21, 71],
       [53, -1, -1]])

In [9]:
#Write a function to calculate the row-wise sum and column-wise sum of a given 4x4 NumPy array.

b = np.random.randint(1,11,(4,4))
b

row_sum = b.sum(axis=0)
col_sum = b.sum(axis=1)
print("sum of row = ",row_sum)
print("sum of col = ",col_sum)

sum of row =  [17 17 25 25]
sum of col =  [21 15 32 16]


In [15]:
#Create a 1D NumPy array with 20 equally spaced values between 0 and 1. Then, reshape it into a 4x5 2D array.

c = np.linspace(0,1,20)
c
c_reshape = c.reshape(4,5)
c_reshape

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632],
       [0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421],
       [0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211],
       [0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])

In [21]:
#Given two NumPy arrays, A and B, perform the following operations:

    #Element-wise addition
    #Element-wise multiplication
    #Matrix multiplication

a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))

    #Element-wise addition
a+b
    #Element-wise multiplication
a*b
    #Matrix multiplication
matmul = np.matmul(a,b)
matmul


array([[ 74,  53,  53],
       [160, 128,  80],
       [ 54,  43,  27]])