In [8]:
import numpy as np

file = np.genfromtxt('over.txt',delimiter=',')
file

array([[ 45.,   6.,   3.,   8.,   9.,   6.,   6.,  74.,  55.,  20.],
       [ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.],
       [  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.]])

In [9]:
#Boolean Masking and Advanced Masking
file >50

array([[False, False, False, False, False, False, False,  True,  True,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False,  True,  True,
         True]])

In [10]:
file[file>50]

array([ 74.,  55.,  60.,  70.,  80.,  90., 100.,  64.,  81., 100.])

In [11]:
#You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[[1,2,3]]

array([2, 3, 4])

In [12]:
np.any(file>50,axis=0)

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [13]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [14]:
a.shape

(6, 5)

In [ ]:
a[2:4,0:2]
#desired output got!!

array([[11, 12],
       [16, 17]])

In [21]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [27]:
a[0,1:2]

array([2])

In [28]:
a[1,2:3]

array([8])

In [29]:
a[2,3:4]

array([14])

In [30]:
a[3,4:5]

array([20])

In [32]:
#way to get those outputs at a time
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [33]:
a[[0],[3,4]]

array([4, 5])

In [39]:
a[[4],[3,4]]

array([24, 25])

In [40]:
a[[5],[3,4]]

array([29, 30])

In [46]:
#unified output
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])