In [8]:
import numpy as np

file = np.genfromtxt('over.txt',delimiter=',')
file

array([[ 45.,   6.,   3.,   8.,   9.,   6.,   6.,  74.,  55.,  20.],
       [ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.],
       [  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.]])

In [9]:
#Boolean Masking and Advanced Masking
file >50

array([[False, False, False, False, False, False, False,  True,  True,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False,  True,  True,
         True]])

In [10]:
file[file>50]

array([ 74.,  55.,  60.,  70.,  80.,  90., 100.,  64.,  81., 100.])

In [11]:
#You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[[1,2,3]]

array([2, 3, 4])

In [12]:
np.any(file>50,axis=0)

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [13]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [14]:
a.shape

(6, 5)

In [ ]:
a[2:4,0:2]
#desired output got!!

array([[11, 12],
       [16, 17]])