In [1]:
#Statistics
import numpy as np

static = np.array([[1,2,3],[4,5,6]])
static

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#finding minimum
np.min(static)


6

In [7]:
#finding maximum
np.max(static)

6

In [9]:
#finding min ro vice
np.max(static,axis=0)

array([4, 5, 6])

In [11]:
#finding sum
np.sum(static)

21

In [12]:
np.sum(static,axis=0)

array([5, 7, 9])

In [13]:
np.sum(static,axis=1)

array([ 6, 15])