In [2]:
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,2,2),dtype = 'int32')
# the data type of the elements is explicitly set to int32 (32-bit integer).

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [7]:
np.full((2,2),99)
#creates a 2-dimensional array of shape (2, 2) where all elements are initialized to the value 99.

array([[99, 99],
       [99, 99]])