In [2]:
import numpy as np
np.zeros((2,3)) 


array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
M = np.ones((4,2,2),dtype = 'int32')
M
# the data type of the elements is explicitly set to int32 (32-bit integer).

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
np.full((2,2),99)
#creates a 2-dimensional array of shape (2, 2) where all elements are initialized to the value 99.
#The primary purpose of np.full() is to create an array of a specific shape, filled with a value of your choice.

array([[99, 99],
       [99, 99]])

In [10]:
a = np.array((1,2,3,4))

np.full_like(a,4)

array([4, 4, 4, 4])

In [13]:
v = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
np.full_like(v.shape,4)

array([4, 4])

In [4]:
d = np.random.rand(4,2,3)
d.shape
d.itemsize

#it will give a matrix of 4 sets  in depth of containing matrix each 2 rows and 3 three columns

8

In [19]:
np.random.rand(4,4)

array([[0.28645656, 0.83451788, 0.71157869, 0.16197085],
       [0.87673751, 0.21446522, 0.23114165, 0.32015384],
       [0.41162857, 0.00970989, 0.08266983, 0.44085816],
       [0.82250296, 0.53683298, 0.27143252, 0.72325365]])

In [ ]:
#array with random integrs
np.random.randint(7,size=(2,8))
#ach element in the array is a random integer between 0 and 6 & the resulting array has 2 rows and 8 columns,

array([[3, 1, 2, 6, 2, 1, 2, 3],
       [5, 2, 6, 1, 3, 5, 3, 5]])

In [ ]:
np.random.randint(3,8,size=(4,4))
#it will print numbers between range from 3 to 7

array([[7, 3, 5, 5],
       [7, 4, 4, 6],
       [3, 6, 7, 5],
       [5, 7, 4, 3]])

In [20]:
#negative numbers in matrix
np.random.randint(-4,8,size=(3,3))

array([[ 5,  0,  0],
       [ 6, -2,  5],
       [ 4,  5,  6]])

In [ ]:
#identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#Repeating Array
j = np.array([1,2,3])
r1 = np.repeat(j,2)
print(r1)

[1 1 2 2 3 3]


In [31]:
f = np.array([[4,5,6]])
r2 = np.repeat(f,2,axis=0)
print(r2)
#printing reepeating elemnts in symmetrical axis

[[4 5 6]
 [4 5 6]]


In [32]:
g = np.array([[7,8,9]])
r3 = np.repeat(g,3,axis = 1)
print(r3)

[[7 7 7 8 8 8 9 9 9]]
